Styling #2
drinkingandcoding/twotop pull request #19
Opened 2022-09-22 15:27 UTC by epwinchell

Nav styling tweaks and var clean-up

![Screen Shot 2022-09-22 at 11 23 44 AM](https://user-images.githubusercontent.com/1287144/191788564-3324e616-e006-4362-b835-ef109e16a541.png)

2022-09-22 15:43 UTC, ryelo requested changes

2022-09-22 15:43 UTC, ryelo commented on src/app.css
> +  --orange: #F16c20;
can you use hsla for this?

2022-09-22 15:43 UTC, ryelo commented on src/lib/header/Header.svelte
> +    border: 1px var(--orange) solid;
let's not use a border for this until i figure out the dark mode stuff

2022-09-22 17:31 UTC, epwinchell commented
> Another comment: I see that changing something in the header removes the underline from the links not touching the bottom of the header, can we keep that?
> 
> I think changing the logo size and the padding bottom on that should fix it so that all the things in the header line up vertically
> 
> example ![Screen Shot 2022-09-22 at 11 45 05 AM](https://user-images.githubusercontent.com/12520842/191792658-7beab8ee-cd51-4bb9-95c6-28df764c0e33.png)

I’m not a 100% sure what you’re saying here: I put the default header bottom-padding back, but adding padding to the logo, won't center menu items vertically.

![Screen Shot 2022-09-22 at 11 33 52 AM](https://user-images.githubusercontent.com/1287144/191812314-9709b727-6182-4d4e-bc4f-b2ab5942fd69.png)

2022-09-23 12:25 UTC, ryelo approved these changes

2022-09-23 12:25 UTC, merged